language: python
python:
    - "3.6"

cache: pip3

install:
    - pip3 install -r requirements.txt

env:
    - SECRET="\xe5\x9c\xd2B\xa8+O>\x84\xeb\xa0\xbcsA'\xf9\xa1L\x83\x1b\xfc\x14!\xac" DATABASE_URL="dbname='politico_db' user='postgres' password='postgres' host='localhost' port=5432" TEST_DATABASE_URL="dbname='politico_test_db' user='postgres' password='postgres' host='localhost' port=5432"

services:
    - postgresql

before_script:
    - psql -c 'create database politico_test_db;' -U postgres
    - psql -c 'create database politico_db;' -U postgres

script:
    - coverage run --source app/tests/v2/ -m pytest

after_success:
    - coveralls

