language: python
python:
    - "3.6"

cache: pip3

install:
    - pip3 install -r requirements.txt

services:
    - postgresql
    
before_script:
    - psql -c 'create database politico_test_db;' -U postgres
    - psql -c 'create database politico_db;' -U postgres

script:
    - coverage run --source app/tests/ -m pytest

after_success:
    - coveralls
